name: CI
on:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          workflow_conclusion: success
          branch: workflow
          path: dynophores_webclient
          repo: nadja-mansurov/dyno_webapp
          name: code-build

      - uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          branch: gh-pages
          cwd: './dynophores_webclient'
          message: 'Update prod'
          push: true
          remove: './dynophores_webclient/**'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .