name: CI
on:
  push:
    branches: [gh-pages]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove Files
        uses: JesseTG/rm@v1.0.2
        with:
          path: dynophores_webclient/

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          workflow_conclusion: success
          branch: main
          path: dynophores_webclient
          repo: nadja-mansurov/dyno_webapp
          name: code-build
          
      - uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          branch: gh-pages
          cwd: './dynophores_webclient'
          message: 'Update prod'
          push: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .